### PR TITLE
add datetime to version

### PR DESCRIPTION
**Pull request by InLaw**

### CODE REVIEW

**Comment by DavHau** [comment]
Currently the this version is read by the cli tool and used to reference a branch or tag for mach-nix. Therefore this change would break the cli tool

**Comment by InLaw** [comment]
I thought something like this - do you have the code link/reference where the logic is loacted?
- shouldn't ci break with that change?

**Comment by DavHau** [comment]
CI uses a hack where it sets the mach-nix version via environment variable. therefore it is not affected by this.

**Comment by InLaw** [comment]
where is the code bit in CI that does the trick (any line reference)?

**Comment by DavHau** [comment]
https://github.com/DavHau/mach-nix/blob/fdd7bec457fa7319acc09ae287daee3ee60c5c76/.github/workflows/CI_NixPy.yml#L58

**Comment by InLaw** [comment]
I'm not sure how you set GITHUB_SHA (reading `/mach_nix/VERSION`)?

```
# GITHUB_SHA="master.20210610.0919"
MACHNIX_VERSION="${GITHUB_SHA%%.*}"
echo $MACHNIX_VERSION
```

**Comment by DavHau** [comment]
I do not. mach-nix reads `MACHNIX_VERSION` if defined instead of reading /mach_nix/VERSION (in run.py).
I just set MACHNIX_VERSION to the value of GITHUB_SHA which results in /mach_nix/VERSION being ignored

**Pull request closed without merging**
