### PR TITLE
chore: package as nix flake

### PR DESCRIPTION
**Pull request by blaggacao**
1. `nix-env -iA nixpkgs.nixFlakes`
2. 
```console
$ cat ~/.config/nix/nix.conf
experimental-features = nix-command flakes
```
3. `nix shell --show-trace`

<details>

```console
$ nix shell --show-trace
while evaluating the attribute 'packages.mach-nix.mach-nix' at /nix/store/g75adbd9wjxcvlm7mxykc135jz7cljz0-source/default.nix:21:3:
while evaluating anonymous function at /nix/store/g75adbd9wjxcvlm7mxykc135jz7cljz0-source/mach_nix/nix/python.nix:1:1, called from /nix/store/g75adbd9wjxcvlm7mxykc135jz7cljz0-source/default.nix:3:12:
while evaluating anonymous function at /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/pkgs/top-level/impure.nix:15:1, called from /nix/store/g75adbd9wjxcvlm7mxykc135jz7cljz0-source/default.nix:2:10:
while evaluating anonymous function at /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/pkgs/top-level/default.nix:20:1, called from /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/pkgs/top-level/impure.nix:84:1:
while evaluating anonymous function at /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/pkgs/stdenv/booter.nix:42:1, called from /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/pkgs/top-level/default.nix:123:10:
while evaluating 'dfold' at /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/pkgs/stdenv/booter.nix:60:27, called from /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/pkgs/stdenv/booter.nix:136:4:
while evaluating 'go' at /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/pkgs/stdenv/booter.nix:63:18, called from /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/pkgs/stdenv/booter.nix:72:13:
while evaluating 'imap1' at /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/lib/lists.nix:116:14, called from /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/pkgs/stdenv/booter.nix:78:30:
while evaluating 'reverseList' at /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/lib/lists.nix:393:17, called from /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/pkgs/stdenv/booter.nix:85:6:
while evaluating anonymous function at /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/pkgs/stdenv/default.nix:7:1, called from /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/pkgs/top-level/default.nix:119:12:
while evaluating 'elaborate' at /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/lib/systems/default.nix:17:15, called from /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/pkgs/top-level/default.nix:60:17:
while evaluating 'foldl' at /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/lib/lists.nix:80:20, called from /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/lib/systems/default.nix:127:13:
while evaluating 'foldl'' at /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/lib/lists.nix:82:16, called from /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/lib/lists.nix:86:8:
while evaluating the attribute 'parsed.abi.assertions' at /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/lib/systems/default.nix:22:7:
while evaluating 'mkSystemFromString' at /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/lib/systems/parse.nix:440:24, called from /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/lib/systems/default.nix:22:16:
while evaluating 'mkSkeletonFromList' at /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/lib/systems/parse.nix:367:24, called from /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/lib/systems/parse.nix:440:49:
while evaluating 'splitString' at /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/lib/strings.nix:382:23, called from /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/lib/systems/parse.nix:440:69:
while evaluating 'recurse' at /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/lib/strings.nix:392:24, called from /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/lib/strings.nix:403:7:
while evaluating 'addContextFrom' at /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/lib/strings.nix:369:23, called from /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/lib/strings.nix:385:11:
while evaluating the attribute 'system' at /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/pkgs/top-level/impure.nix:90:30:

error: --- EvalError --------------------------------------------------------------------------------------- nix
in file: /nix/store/q04pywh9qywl1dxwdvsywmssasrhlv4d-nixpkgs/pkgs/top-level/impure.nix (90:39)

attribute 'currentSystem' missing
```

</details>

While trying to wrap my head arround the emerging error, I din't find the root couse.
Nevertheless, I thought, this might be some hands on kowledge sharing on [nix flakes](https://github.com/tweag/rfcs/blob/flakes/rfcs/0049-flakes.md).
See also: https://www.tweag.io/blog/2020-05-25-flakes/

### CODE REVIEW

**Comment by blaggacao** [comment]
See furthermore _one_ (possible) `devShell` pattern with flake: https://github.com/nix-community/flake-nimble/blob/22e4e490b5d5ad15e78c9225022d0dc43d65af8a/flake.nix#L55-L64

**Comment by blaggacao** [comment]
Interestingly trying to import mach-nix in a "legacy-ish" manner in a flake yields the same error:

```nix
with import mach-nix; mkPython
```

<details>

```nix
{

    description = "A base flake for k8s development";

    inputs = {
        flake-utils.url = "github:numtide/flake-utils";
        kube-score.url = "github:blaggacao/kube-score";
        mach-nix = {
            type = "github";
            owner = "DavHau";
            repo = "mach-nix";
            flake = false;
        };
    };

    outputs = { self, nixpkgs, flake-utils, kube-score, mach-nix }:
        flake-utils.lib.eachDefaultSystem (system:
            let
            	pkgs = import nixpkgs { inherit system; };
                commitizenPython = with import mach-nix; mkPython {
                    python = pkgs.python38;
                    requirements = ''
                      commitizen
                      setuptools
                    '';
                };

            in rec {
                packages.commitizenPython = commitizenPython;
                packages.kube-score = kube-score;
                defaultPackage = pkgs.mkShell { buildInputs = [
                    packages.commitizenPython
                    packages.kube-score

                ]; };
            }
        );
}
```

</details>

**Comment by DavHau** [comment]
Recently I was thinking that it would be amazing if mach-nix would provide a flakes gateway directly to pypi.
So that every package on pypi could be acquired via:
```
nix shell github:DavHau/mach-nix#{package}
```

**Comment by DavHau** [comment]
This should work for now. Adding all available python packages to the flakes output could be done in the future.

**Comment by DavHau** [comment]
The only side effect now is, that mach-nix requires at least an empty attrset to be passed during importing.

**Comment by blaggacao** [comment]
Cool! It's amazing flakes are coming to mach-nix. :+1:

**Pull request merged**
