### PR TITLE
Update dependencies of python packages specified in packagesExtra in mkPython.

### PR DESCRIPTION
**Pull request by tomprince**
Otherwise, it is likely that there will be collisions building the python environment,
as the dependencies of packages in packagesExtra won't match with the dependencies
calculated by mach-nix.

As a side-effect, this also causes the dependencies of mach-nix built packages included
by the `nixpkgs` provider to be included in dependency resolution.

### CODE REVIEW

**Comment by DavHau** [comment]
Thanks, this is a great improvement!
There seems to be a infinite recursion with `providers = providers // extra_pkgs_providers;`

> As a side-effect, this also causes the dependencies of mach-nix built packages included
by the nixpkgs provider to be included in dependency resolution.

It would be amazing if that would work for all nixpkgs python packages. Currently there is a lot of complexity in the nix code generated by `overrides_geerator.py`, trying to prevent collisions etc, which is sometime unreliable. I wonder if it would improve the situation if we scan nixpkgs python packages for their requirements already in `nixpkgs-json.nix` and include those into the resolution somehow.

**Comment by tomprince** [comment]
> There seems to be a infinite recursion with `providers = providers // extra_pkgs_providers;`

I didn't expect it to be infinite recursion, since `extra_pkgs_providers` depends only on the keys of `extra_pkgs_python_attrs` and the attribute you mention only occurs in the values of it. You can test this by evaluating `:p let x = { "a" = builtins.mapAttrs (n: v: n) x; }; in x` in `nix repl`. But I guess that depends on the `.pname` of the packages there, and that can't be evaluated. I'll remove this change.

> > As a side-effect, this also causes the dependencies of mach-nix built packages included
> > by the nixpkgs provider to be included in dependency resolution.
> 
> It would be amazing if that would work for all nixpkgs python packages. Currently there is a lot of complexity in the nix code generated by `overrides_generator.py`, trying to prevent collisions etc, which is sometime unreliable. I wonder if it would improve the situation if we scan nixpkgs python packages for their requirements already in `nixpkgs-json.nix` and include those into the resolution somehow.

Are you proposing determining the requirements based on `propoagatedBuildInputs` et al? I don't think that is preferable to what is done currently. I think the best we could get is unversioned dependencies or explicitly pinned dependencies, both of which are worse than getting the dependencies from the sdist or wheel dependencies.

> Currently there is a lot of complexity in the nix code generated by `overrides_generator.py`, trying to prevent collisions etc, which is sometime unreliable.

This PR should help with some cases of that. Specifically, when a mach-nix built package is include in a `mkPython` environment via `packagesExtra` and some of it dependencies are resolved differently with the extra constraints added by `mkPython`. This is exactly the case I ran into, where black's dependency on `tomli<2` (now fixed) caused a different version to be pulled for `mkPython` than for a local package (which pulled in tomli via setuptools-scm in one of its dependencies.

**Comment by DavHau** [comment]
> > There seems to be a infinite recursion with `providers = providers // extra_pkgs_providers;`
> 
> I didn't expect it to be infinite recursion, since `extra_pkgs_providers` depends only on the keys of `extra_pkgs_python_attrs` and the attribute you mention only occurs in the values of it. You can test this by evaluating `:p let x = { "a" = builtins.mapAttrs (n: v: n) x; }; in x` in `nix repl`. But I guess that depends on the `.pname` of the packages there, and that can't be evaluated. I'll remove this change.

I think the problem is much simpler. You referenced the variable itself while declaring the variable.
The problem can be re-produced in the repl:
```
nix-repl> let providers = providers // {}; in providers
error: infinite recursion encountered
```

**Comment by tomprince** [comment]
> I think the problem is much simpler. You referenced the variable itself while declaring the variable.

That doesn't always cause infinite recursion, as the example in my comment demonstrates. If the part of the value where the variable is used doesn't itself evaluate that part of the value, you won't get infinite recursion. Both nixpkgs overlays, and nixos configuration depend heavily on this fact.

**Pull request merged**
