### PR TITLE
Match macosx_11_0_arm64.wheel

### PR DESCRIPTION
**Pull request by nasyxx**
e.g. `numpy-1.21.4-cp310-cp310-macosx_11_0_arm64.whl`  https://pypi.org/project/numpy/#files

### CODE REVIEW

**Comment by DavHau** [comment]
Thanks. The problem I see with this is that it is now possible to get arm64 wheels on x86_64 and vice versa. It should probably just use the `self.platform` variable, like it is done for the linux wheels.
I am not sure though if `self.platform` yields `aarch64` or `arm64` in case of arm. That'd need to be checked first and potentially mapped correctly

**Comment by nasyxx** [comment]
> Thanks. The problem I see with this is that it is now possible to get arm64 wheels on x86_64 and vice versa. 

Sounds bad.

> I am not sure though if `self.platform` yields `aarch64` or `arm64` in case of arm. That'd need to be checked first and potentially mapped correctly

If you need to test on an arm mac machine, just let me know.

**Comment by NikolayTach** [comment]
[issuecomment-985997686](https://github.com/henryken/techleadjournal.dev-comments/issues/6#issuecomment-985997686)

**Comment by jared-w** [comment]
@DavHau , it's `arm64` according to: https://github.com/google/or-tools/issues/2332#issuecomment-760124936

So it should be able to naively be mapped, same as the linux ones currently are.

**Comment by didierck** [comment]
Hello,
For those interested, I have managed to compile or tools python 9.2.9972  on my M1 without SCIP
[ortools-9.2.9972-cp39-cp39-macosx_11_0_arm64.whl.zip](https://github.com/DavHau/mach-nix/files/7929033/ortools-9.2.9972-cp39-cp39-macosx_11_0_arm64.whl.zip).
Let me know if you need more information.

**Pull request merged**
